[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build]
  command = "pip install -r requirements.txt && python -m uvicorn app.main:app --reload"
  functions = "netlify/functions"
  publish = "app"

[dev]
  command = "python -m uvicorn app.main:app --reload"
  port = 8000
